# DESCRIPTION:
# Generates a visualization of the results from the MCMC algorithm for
# for the data under analysis.
# Plot environmental space (2 dimensions) using the background points
# selected for the species together with 1) the occurrence points and
# 2) the ellipses that were generated by the MCMC algorithm and that
# represent a sample from the posterior distribution.

# ARGUMENTS: see NOTES
# th --- vector that contains the current values of parameters mu and A
# info --- the output of the MCMC algorithm function (a matrix with all the values for mu and A from the posterior distribution)
# from --- a number that indicates the start point to choose from info (burn-in time)
# thin --- a number equals to number of values to skip before selecting the next values from info
# col --- character vector definig the colors of [1] the background and [2] the occurrence points
# lev --- a value in (0,1) indicating the confidence level that the ellipses represent in the MVN distribution
# ... --- any other parameter that can be used by the functions plot, lines, points

# OUTPUTS: see NOTES
# A plot that shows the environmental background, the occurrence points and
# a sample of ellipses from the posterior distribution with different colors.

# NOTES:
# Some variables that contain the species data must be defined before using this function.

# If th not NULL, then also plot a Bivariate Normal with parameters th (See function Supp above)
# It's posible to add other valid parameters for the function contour or change the color (See function PlotBN above)
PlotIterations <- function( th, info, from, thin, col, lev, ...) 
{
  # plot background and occurrence points

  # check that th contains a valid value and use it to plot the first ellipse

  # calculate the value of the posterior distribution for each row of info

  # find the MAP and sort the posterior values
  # plot all the ellipses using a different color according to their posterior value
}
